export type Language = 'es' | 'en';

export const resumeLabels = {
  es: {
    summary: 'Resumen Profesional',
    aboutMe: 'Sobre mí',
    experience: 'Experiencia',
    education: 'Educación',
    skills: 'Habilidades',
    projects: 'Proyectos',
    certifications: 'Certificaciones',
    languages: 'Idiomas',
    contact: 'Contacto',
    phone: 'Teléfono',
    location: 'Ubicación',
    present: 'Actual',
    inField: 'en',
    noExperience: 'Sin experiencia',
    noEducation: 'Sin educación',
    docSubject: 'Currículum Vitae',
  },
  en: {
    summary: 'Professional Summary',
    aboutMe: 'About Me',
    experience: 'Experience',
    education: 'Education',
    skills: 'Skills',
    projects: 'Projects',
    certifications: 'Certifications',
    languages: 'Languages',
    contact: 'Contact',
    phone: 'Phone',
    location: 'Location',
    present: 'Present',
    inField: 'in',
    noExperience: 'No experience',
    noEducation: 'No education',
    docSubject: 'Resume',
  },
} as const;
